# Generated by Django 6.0.5 on 2026-05-27 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del curso')),
                ('jornada', models.CharField(max_length=20, verbose_name='Jornada')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('email_apoderado', models.EmailField(max_length=254, verbose_name='Email del apoderado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='escuela_app.curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de término')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Eventos de agenda',
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='check_evento_hora_fin_mayor_hora_inicio')],
            },
        ),
        migrations.CreateModel(
            name='RecursoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activo', models.CharField(max_length=50, unique=True, verbose_name='Código activo')),
                ('nombre_articulo', models.CharField(max_length=100, verbose_name='Nombre del artículo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('stock_actual', models.IntegerField(verbose_name='Stock actual')),
            ],
            options={
                'verbose_name': 'Recurso de inventario',
                'verbose_name_plural': 'Recursos de inventario',
                'constraints': [models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='check_recurso_stock_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de asistencia')),
                ('estado_asistencia', models.CharField(choices=[('P', 'Presente'), ('X', 'Ausente'), ('/', 'Observación'), ('A', 'Atraso')], max_length=1, verbose_name='Estado de asistencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='escuela_app.estudiante')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
            },
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.CheckConstraint(condition=models.Q(('sexo__in', ['M', 'F'])), name='check_estudiante_sexo_valido'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['fecha', 'estudiante'], name='idx_registro_fecha_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.CheckConstraint(condition=models.Q(('estado_asistencia__in', ['P', 'X', '/', 'A'])), name='check_registro_estado_asistencia_valido'),
        ),
    ]
