# Generated by Django 6.0.5 on 2026-05-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='jornada',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('nocturna', 'Nocturna')], max_length=20, verbose_name='Jornada'),
        ),
    ]
