# Generated by Django 6.0.5 on 2026-05-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_app', '0002_alter_curso_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoinventario',
            name='categoria',
            field=models.CharField(choices=[('aseo', 'Materiales de aseo'), ('oficina_pedagogicos', 'Materiales de oficina y pedagógicos')], max_length=50, verbose_name='Categoría'),
        ),
    ]
