# Generated by Django 5.2.15 on 2026-09-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_app', '0003_alter_recursoinventario_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='motivo_atraso',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del atraso'),
        ),
    ]
